// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Hardcoded to external Supabase project (vgfazkvsazrfxkfqczer)
const SUPABASE_URL = "https://vgfazkvsazrfxkfqczer.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_0KbDbtP0IKzNIDEcqCDihA_XYwqhOY-";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});